version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: unless-stopped
    env_file:
      - .env

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "${UI_PORT}:${UI_PORT}"
    restart: unless-stopped
    depends_on:
      - api
    env_file:
      - .env

